language: node_js
services:
- mongodb
- redis-server
node_js:
- '0.10'
before_script: npm install --dev
script: npm test
env:
  global:
  - ANYFETCH_API_ID="anyfetch-id"
  - ANYFETCH_API_SECRET="anyfetch-secret"
  - PROVIDER_URL="http://localhost:8000"
  - SALESFORCE_CONCURRENCY="5"
  - secure: OslpGGv5H3v1wOrvIlxDt4gV1T7NYwy9lAYj1OOvq1CQ7DMZfBUTpM7sH62lAgKI5L6K1HGKibrEdEpdumCYgegWz3zDtlOgTVQzkDXaY8i+8Lk6jmjD9XWf7iq+zymdNjf7R1ZAfhxbezljdwSnJJY2oU+vekZOgJiBtsdkur8=
  - secure: UisUDck/vFEczfscqlKMl3EyuS4aUJzD7ytRDwBX3Me2aqeySWN1Mnu83cHqkjazCLTpxAyNvopYjp1j7dtAYQX3huo96QyocL+44TyRMIcvkUlVAi8whWgk4v5ZBuL0+/1lmlUKv0YipNf1h8RxaAHWVAiu5R9qe2n6MUpg7Lk=
  - secure: eAidrjrRxY8NUTKRR8AykkW+7S0j8rRPrzfwZ/MmMNisEZp5YguqqN3aLcQ5y/eXNjNMMqxjfcwdCbDQIkFQ2XYVwbXz1MBgnSZzqjmOywf3AiIVyIXfn0XqFhyuWutecSyV6tcNWUShyNuDNjCUnErAlERLEJrtibB4Xwlz7SY=
